
services:
  db:
    image: postgres:15
    env_file: .env
  backend:
    build: ./restaurantapp
    command: gunicorn restauranteapp.wsgi:application
    volumes:
      - ./restaurantapp:/app
    env_file: .env
    depends_on: [db]
  frontend:
    build: ./frontend
    command: ng serve --host 0.0.0.0
    ports:
      - '4200:4200'
    depends_on: [backend]
