# Generated by Django 5.0.6 on 2025-07-02 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_login_end_and_more'),
        ('attendance', '0002_initial'),
    ]

    operations = [
    ]
