# Generated by Django 5.2.1 on 2025-06-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='login_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='login_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
